var car = 'subaru';
console.log("is car == 'subaru' ? i predict true.");
console.log(car == 'subaru');
console.log("is car === 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("is car != 'subaru'? I predict false.");
console.log(car != 'subaru');
console.log("is car !== 'subaru'? I predict false.");
console.log(car !== 'subaru');
console.log("is car < 'subaru'? I predict false.");
console.log(car < 'subaru');
console.log("is car > 'subaru'? I predict false.");
console.log(car > 'subaru');
console.log("is car <= 'subaru'? I predict true.");
console.log(car <= 'subaru');
console.log("is car >= 'subaru'? I predict true.");
console.log(car >= 'subaru');
console.log("is car? I predict true.");
console.log(car);
console.log("is !car? I predict false.");
console.log(!car);
